version: "3"

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:inception
    container_name: mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:inception
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx/
    image: nginx:inception
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    
volumes:
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/revieira/data/mariadb

  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/revieira/data/wordpress

networks:
  inception:
    name: inception
