version: "3"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        # - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    image: mariadb:inception
    container_name: mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_ROOT_PASSWORD

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:inception
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    env_file: .env
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD

  nginx:
    build: ./requirements/nginx/
    image: nginx:inception
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    
volumes:
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/revieira/data/mariadb

  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/revieira/data/wordpress

networks:
  inception:
    name: inception
