version: "3"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    image: mariadb:inception
    container_name: mariadb
    restart: on-failure
    healthcheck:
      test: mysqladmin ping -h localhost -u root
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception
    env_file: .env
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:inception
    container_name: wordpress
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - inception
    env_file: .env
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - WP_ROOT_USER
      - WP_ROOT_EMAIL
      - WP_ROOT_PASSWORD
      - WP_USER
      - WP_EMAIL
      - WP_PASSWORD

  nginx:
    build: ./requirements/nginx/
    image: nginx:inception
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/wordpress
      - adminer-volume:/var/www/adminer
    networks:
      - inception
    ports:
      - 443:443

  adminer:
    build: ./requirements/bonus/adminer/
    image: adminer:inception
    container_name: adminer
    restart: on-failure
    volumes:
      - adminer-volume:/var/www/adminer
    depends_on:
      - mariadb
    networks:
      - inception

  static-website:
    build: ./requirements/bonus/static-website/
    image: static-website:inception
    container_name: static-website
    restart: on-failure
    networks:
      - inception
    ports:
      - 4242:4242

  uptime-kuma:
    build: ./requirements/bonus/uptime-kuma/
    image: uptime-kuma:inception
    container_name: uptime-kuma
    restart: on-failure
    depends_on:
      - nginx
    volumes:
      - uptime-kuma-volume:/uptime-kuma/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception
    ports:
      - 3001:3001
    
volumes:
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/revieira/data/mariadb

  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/revieira/data/wordpress

  adminer-volume:
    name: adminer-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/revieira/data/adminer

  uptime-kuma-volume:
    name: uptime-kuma-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/revieira/data/uptime-kuma

networks:
  inception:
    name: inception
